{{- if and (.Values.plugin.patcherServiceAccount.create) (.Values.plugin.jobs.patchConsoles.enabled) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "test-openshift-plugin.patcherServiceAccountName" . }}
  labels:
    {{- include "test-openshift-plugin.labels" . | nindent 4 }}
  {{- with .Values.plugin.patcherServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
