apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: {{ template "camel-openshift-console-plugin.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "camel-openshift-console-plugin.labels" . | nindent 4 }}
spec:
  displayName: {{ default (printf "%s Plugin" (include "camel-openshift-console-plugin.name" .)) .Values.plugin.description }}
  i18n: 
    loadType: Preload
  backend:
    type: Service
    service:
      name: {{ template "camel-openshift-console-plugin.name" . }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.plugin.port }}
      basePath: {{ .Values.plugin.basePath }}