{{- if .Values.plugin.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "camel-openshift-console-plugin.serviceAccountName" . }}
  labels:
    {{- include "camel-openshift-console-plugin.labels" . | nindent 4 }}
  {{- with .Values.plugin.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
